# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atuoconfig.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.configpage = QtWidgets.QTabWidget(self.centralwidget)
        self.configpage.setGeometry(QtCore.QRect(30, 30, 1031, 761))
        self.configpage.setObjectName("configpage")
        self.stpconfig = QtWidgets.QWidget()
        self.stpconfig.setObjectName("stpconfig")
        self.pushButton_ok = QtWidgets.QPushButton(self.stpconfig)
        self.pushButton_ok.setGeometry(QtCore.QRect(770, 690, 75, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(self.stpconfig)
        self.pushButton_cancel.setGeometry(QtCore.QRect(890, 690, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.groupBox_checkpoint = QtWidgets.QGroupBox(self.stpconfig)
        self.groupBox_checkpoint.setGeometry(QtCore.QRect(10, 170, 381, 211))
        self.groupBox_checkpoint.setObjectName("groupBox_checkpoint")
        self.checkBox_network = QtWidgets.QCheckBox(self.groupBox_checkpoint)
        self.checkBox_network.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.checkBox_network.setObjectName("checkBox_network")
        self.checkBox_ts = QtWidgets.QCheckBox(self.groupBox_checkpoint)
        self.checkBox_ts.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.checkBox_ts.setObjectName("checkBox_ts")
        self.checkBox_cpri = QtWidgets.QCheckBox(self.groupBox_checkpoint)
        self.checkBox_cpri.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.checkBox_cpri.setObjectName("checkBox_cpri")
        self.checkBox_iqdata = QtWidgets.QCheckBox(self.groupBox_checkpoint)
        self.checkBox_iqdata.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.checkBox_iqdata.setObjectName("checkBox_iqdata")
        self.groupBox_configpoint = QtWidgets.QGroupBox(self.stpconfig)
        self.groupBox_configpoint.setGeometry(QtCore.QRect(20, 400, 371, 231))
        self.groupBox_configpoint.setObjectName("groupBox_configpoint")
        self.checkBox_cfgnet = QtWidgets.QCheckBox(self.groupBox_configpoint)
        self.checkBox_cfgnet.setGeometry(QtCore.QRect(20, 30, 141, 20))
        self.checkBox_cfgnet.setObjectName("checkBox_cfgnet")
        self.checkBox_cfgxplink = QtWidgets.QCheckBox(self.groupBox_configpoint)
        self.checkBox_cfgxplink.setGeometry(QtCore.QRect(20, 60, 141, 20))
        self.checkBox_cfgxplink.setObjectName("checkBox_cfgxplink")
        self.checkBox_cfgruma = QtWidgets.QCheckBox(self.groupBox_configpoint)
        self.checkBox_cfgruma.setGeometry(QtCore.QRect(20, 90, 141, 20))
        self.checkBox_cfgruma.setObjectName("checkBox_cfgruma")
        self.groupBox_log = QtWidgets.QGroupBox(self.stpconfig)
        self.groupBox_log.setGeometry(QtCore.QRect(470, 170, 521, 481))
        self.groupBox_log.setObjectName("groupBox_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.groupBox_log)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 30, 501, 441))
        self.textEdit_log.setObjectName("textEdit_log")
        self.connection = QtWidgets.QGroupBox(self.stpconfig)
        self.connection.setGeometry(QtCore.QRect(12, 13, 881, 141))
        self.connection.setObjectName("connection")
        self.label_user = QtWidgets.QLabel(self.connection)
        self.label_user.setGeometry(QtCore.QRect(248, 21, 47, 21))
        self.label_user.setTextFormat(QtCore.Qt.RichText)
        self.label_user.setObjectName("label_user")
        self.label_serverip = QtWidgets.QLabel(self.connection)
        self.label_serverip.setGeometry(QtCore.QRect(18, 17, 81, 31))
        self.label_serverip.setTextFormat(QtCore.Qt.RichText)
        self.label_serverip.setScaledContents(False)
        self.label_serverip.setWordWrap(False)
        self.label_serverip.setObjectName("label_serverip")
        self.lineEdit_passwd = QtWidgets.QLineEdit(self.connection)
        self.lineEdit_passwd.setGeometry(QtCore.QRect(510, 21, 131, 21))
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.lineEdit_serverip = QtWidgets.QLineEdit(self.connection)
        self.lineEdit_serverip.setGeometry(QtCore.QRect(98, 22, 131, 21))
        self.lineEdit_serverip.setObjectName("lineEdit_serverip")
        self.lineEdit_port = QtWidgets.QLineEdit(self.connection)
        self.lineEdit_port.setGeometry(QtCore.QRect(738, 20, 81, 21))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_user = QtWidgets.QLineEdit(self.connection)
        self.lineEdit_user.setGeometry(QtCore.QRect(290, 21, 131, 21))
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label_port = QtWidgets.QLabel(self.connection)
        self.label_port.setGeometry(QtCore.QRect(688, 20, 41, 21))
        self.label_port.setObjectName("label_port")
        self.pushButton_stpconnection = QtWidgets.QPushButton(self.connection)
        self.pushButton_stpconnection.setGeometry(QtCore.QRect(740, 90, 75, 23))
        self.pushButton_stpconnection.setObjectName("pushButton_stpconnection")
        self.groupBox_session = QtWidgets.QGroupBox(self.connection)
        self.groupBox_session.setGeometry(QtCore.QRect(10, 54, 371, 81))
        self.groupBox_session.setObjectName("groupBox_session")
        self.radioButton_ssh = QtWidgets.QRadioButton(self.groupBox_session)
        self.radioButton_ssh.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_ssh.setObjectName("radioButton_ssh")
        self.radioButton_telnet = QtWidgets.QRadioButton(self.groupBox_session)
        self.radioButton_telnet.setGeometry(QtCore.QRect(100, 40, 82, 17))
        self.radioButton_telnet.setObjectName("radioButton_telnet")
        self.radioButton_ct11 = QtWidgets.QRadioButton(self.groupBox_session)
        self.radioButton_ct11.setGeometry(QtCore.QRect(200, 40, 61, 17))
        self.radioButton_ct11.setObjectName("radioButton_ct11")
        self.radioButton_ftp = QtWidgets.QRadioButton(self.groupBox_session)
        self.radioButton_ftp.setGeometry(QtCore.QRect(300, 39, 51, 20))
        self.radioButton_ftp.setObjectName("radioButton_ftp")
        self.label_passwd = QtWidgets.QLabel(self.connection)
        self.label_passwd.setGeometry(QtCore.QRect(449, 21, 71, 21))
        self.label_passwd.setObjectName("label_passwd")
        self.configpage.addTab(self.stpconfig, "")
        self.dhcpcofig = QtWidgets.QWidget()
        self.dhcpcofig.setObjectName("dhcpcofig")
        self.groupBox_dhcpconfig = QtWidgets.QGroupBox(self.dhcpcofig)
        self.groupBox_dhcpconfig.setGeometry(QtCore.QRect(20, 150, 431, 531))
        self.groupBox_dhcpconfig.setObjectName("groupBox_dhcpconfig")
        self.groupBox_add = QtWidgets.QGroupBox(self.groupBox_dhcpconfig)
        self.groupBox_add.setGeometry(QtCore.QRect(20, 280, 391, 141))
        self.groupBox_add.setObjectName("groupBox_add")
        self.lineEdit_addip = QtWidgets.QLineEdit(self.groupBox_add)
        self.lineEdit_addip.setGeometry(QtCore.QRect(59, 28, 181, 22))
        self.lineEdit_addip.setObjectName("lineEdit_addip")
        self.label_addip = QtWidgets.QLabel(self.groupBox_add)
        self.label_addip.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.label_addip.setObjectName("label_addip")
        self.label_addmac = QtWidgets.QLabel(self.groupBox_add)
        self.label_addmac.setGeometry(QtCore.QRect(10, 90, 55, 16))
        self.label_addmac.setObjectName("label_addmac")
        self.lineEdit_addmac = QtWidgets.QLineEdit(self.groupBox_add)
        self.lineEdit_addmac.setGeometry(QtCore.QRect(60, 90, 181, 22))
        self.lineEdit_addmac.setText("")
        self.lineEdit_addmac.setObjectName("lineEdit_addmac")
        self.groupBox_configchoice = QtWidgets.QGroupBox(self.groupBox_dhcpconfig)
        self.groupBox_configchoice.setGeometry(QtCore.QRect(30, 40, 341, 221))
        self.groupBox_configchoice.setObjectName("groupBox_configchoice")
        self.radioButton_search = QtWidgets.QRadioButton(self.groupBox_configchoice)
        self.radioButton_search.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.radioButton_search.setObjectName("radioButton_search")
        self.radioButton_del = QtWidgets.QRadioButton(self.groupBox_configchoice)
        self.radioButton_del.setGeometry(QtCore.QRect(10, 110, 95, 20))
        self.radioButton_del.setObjectName("radioButton_del")
        self.radioButton_add = QtWidgets.QRadioButton(self.groupBox_configchoice)
        self.radioButton_add.setGeometry(QtCore.QRect(10, 70, 95, 20))
        self.radioButton_add.setObjectName("radioButton_add")
        self.radioButton_modify = QtWidgets.QRadioButton(self.groupBox_configchoice)
        self.radioButton_modify.setGeometry(QtCore.QRect(10, 150, 95, 20))
        self.radioButton_modify.setObjectName("radioButton_modify")
        self.radioButton_backup = QtWidgets.QRadioButton(self.groupBox_configchoice)
        self.radioButton_backup.setGeometry(QtCore.QRect(10, 190, 95, 20))
        self.radioButton_backup.setObjectName("radioButton_backup")
        self.pushButton_cfgok = QtWidgets.QPushButton(self.groupBox_dhcpconfig)
        self.pushButton_cfgok.setGeometry(QtCore.QRect(210, 470, 93, 28))
        self.pushButton_cfgok.setObjectName("pushButton_cfgok")
        self.pushButton_cfgcancel = QtWidgets.QPushButton(self.groupBox_dhcpconfig)
        self.pushButton_cfgcancel.setGeometry(QtCore.QRect(320, 470, 93, 28))
        self.pushButton_cfgcancel.setObjectName("pushButton_cfgcancel")
        self.groupBox_connect = QtWidgets.QGroupBox(self.dhcpcofig)
        self.groupBox_connect.setGeometry(QtCore.QRect(0, 20, 991, 121))
        self.groupBox_connect.setObjectName("groupBox_connect")
        self.label_dhcpip = QtWidgets.QLabel(self.groupBox_connect)
        self.label_dhcpip.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.label_dhcpip.setObjectName("label_dhcpip")
        self.lineEdit_dhcpip = QtWidgets.QLineEdit(self.groupBox_connect)
        self.lineEdit_dhcpip.setGeometry(QtCore.QRect(96, 45, 151, 22))
        self.lineEdit_dhcpip.setObjectName("lineEdit_dhcpip")
        self.lineEdit_dhcpuser = QtWidgets.QLineEdit(self.groupBox_connect)
        self.lineEdit_dhcpuser.setGeometry(QtCore.QRect(324, 48, 151, 22))
        self.lineEdit_dhcpuser.setObjectName("lineEdit_dhcpuser")
        self.label_dhcpuser = QtWidgets.QLabel(self.groupBox_connect)
        self.label_dhcpuser.setGeometry(QtCore.QRect(280, 43, 91, 31))
        self.label_dhcpuser.setObjectName("label_dhcpuser")
        self.lineEdit_dhcppwd = QtWidgets.QLineEdit(self.groupBox_connect)
        self.lineEdit_dhcppwd.setGeometry(QtCore.QRect(620, 48, 151, 22))
        self.lineEdit_dhcppwd.setObjectName("lineEdit_dhcppwd")
        self.label_dhcppwd = QtWidgets.QLabel(self.groupBox_connect)
        self.label_dhcppwd.setGeometry(QtCore.QRect(553, 44, 91, 31))
        self.label_dhcppwd.setObjectName("label_dhcppwd")
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox_connect)
        self.pushButton_connect.setGeometry(QtCore.QRect(860, 80, 93, 28))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.groupBox_dhcplog = QtWidgets.QGroupBox(self.dhcpcofig)
        self.groupBox_dhcplog.setGeometry(QtCore.QRect(480, 150, 511, 531))
        self.groupBox_dhcplog.setObjectName("groupBox_dhcplog")
        self.textEdit_dhcplog = QtWidgets.QTextEdit(self.groupBox_dhcplog)
        self.textEdit_dhcplog.setGeometry(QtCore.QRect(10, 20, 481, 481))
        self.textEdit_dhcplog.setObjectName("textEdit_dhcplog")
        self.configpage.addTab(self.dhcpcofig, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.configpage.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ok.setText(_translate("MainWindow", "OK"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_checkpoint.setTitle(_translate("MainWindow", "Check Point"))
        self.checkBox_network.setText(_translate("MainWindow", "Network"))
        self.checkBox_ts.setText(_translate("MainWindow", "Terminal port"))
        self.checkBox_cpri.setText(_translate("MainWindow", "CPRI "))
        self.checkBox_iqdata.setText(_translate("MainWindow", "IQdata "))
        self.groupBox_configpoint.setTitle(_translate("MainWindow", "Run Scripts"))
        self.checkBox_cfgnet.setText(_translate("MainWindow", "Config Network"))
        self.checkBox_cfgxplink.setText(_translate("MainWindow", "Config Xplink"))
        self.checkBox_cfgruma.setText(_translate("MainWindow", "Config RUMA"))
        self.groupBox_log.setTitle(_translate("MainWindow", "Log"))
        self.connection.setTitle(_translate("MainWindow", "Connection"))
        self.label_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">User:</span></p></body></html>"))
        self.label_serverip.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Server IP:</span></p></body></html>"))
        self.label_port.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Port:</span></p></body></html>"))
        self.pushButton_stpconnection.setText(_translate("MainWindow", "Connection"))
        self.groupBox_session.setTitle(_translate("MainWindow", "Session Choice"))
        self.radioButton_ssh.setText(_translate("MainWindow", "SSH"))
        self.radioButton_telnet.setText(_translate("MainWindow", "TELENT"))
        self.radioButton_ct11.setText(_translate("MainWindow", "RUMA"))
        self.radioButton_ftp.setText(_translate("MainWindow", "FTP"))
        self.label_passwd.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Passwd:</span></p></body></html>"))
        self.configpage.setTabText(self.configpage.indexOf(self.stpconfig), _translate("MainWindow", "STP CONFIG"))
        self.groupBox_dhcpconfig.setTitle(_translate("MainWindow", "DHCP config"))
        self.groupBox_add.setTitle(_translate("MainWindow", "IP info"))
        self.label_addip.setText(_translate("MainWindow", "IP :"))
        self.label_addmac.setText(_translate("MainWindow", "MAC:"))
        self.groupBox_configchoice.setTitle(_translate("MainWindow", "Config"))
        self.radioButton_search.setText(_translate("MainWindow", "Search"))
        self.radioButton_del.setText(_translate("MainWindow", "Delete"))
        self.radioButton_add.setText(_translate("MainWindow", "Add"))
        self.radioButton_modify.setText(_translate("MainWindow", "Modify"))
        self.radioButton_backup.setText(_translate("MainWindow", "Backup"))
        self.pushButton_cfgok.setText(_translate("MainWindow", "OK"))
        self.pushButton_cfgcancel.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_connect.setTitle(_translate("MainWindow", "Connection"))
        self.label_dhcpip.setText(_translate("MainWindow", "DHCP server:"))
        self.label_dhcpuser.setText(_translate("MainWindow", "User:"))
        self.label_dhcppwd.setText(_translate("MainWindow", "Passwd :"))
        self.pushButton_connect.setText(_translate("MainWindow", "Cconnrection"))
        self.groupBox_dhcplog.setTitle(_translate("MainWindow", "Log"))
        self.configpage.setTabText(self.configpage.indexOf(self.dhcpcofig), _translate("MainWindow", "DHCP CONFIG"))





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

